### ISSUE TITLE
异步接口

### ISSUE THREAD

**Issue by ssssssssssss** [AppAdhoc/react-native-adhoc#2]
看到文档中有些接口可能是相同功能，比如：
asynchronousGetFlag
getFlag(String, Any, Function)

getFlag是会阻塞RN的JS还是？看到结果都应该是回调给出的，是否对JS层应该统一？

另，支持async/await?  https://facebook.github.io/react-native/docs/native-modules-ios.html#promises

**Comment by iYiming** [comment]
getFlag 是从本地获取 Flag
asynchronousGetFlag 是从线上获取 Flag

不会阻塞 RN

**Comment by ssssssssssss** [comment]
什么时候应该用本地版本，什么时候用线上版本？区别主要是什么？
