### ISSUE TITLE
更新完sdk iOS 总是请求超时 default 值是什么结果就是什么

### ISSUE THREAD

**Issue by fangasvsass** [AppAdhoc/react-native-adhoc#7]
调用getFlag 方法如果缓存中有值 就一直用这个值是吗？ 即使实验 的流量已经设置为0了
![image](https://user-images.githubusercontent.com/8134572/49989583-a6f46c80-ffb5-11e8-9d0a-1c04b3d3f3af.png)

**Comment by iYiming** [comment]
![](https://user-images.githubusercontent.com/8134572/49989583-a6f46c80-ffb5-11e8-9d0a-1c04b3d3f3af.png)

试验流量已经设置为 0， 手动调用 asynchoronousGetFlag 会返回自己设置的默认值。会经常出现上图请求超时错误么，请保持网络状态良好，再试一次。

**Comment by fangasvsass** [comment]
iOS 所有的实验都是超时，一个实验 a版本和b版本 手机 最开始进入a版本 但是后来a版本流量设置成0 手机还是a版本

**Comment by fangasvsass** [comment]
![image](https://user-images.githubusercontent.com/8134572/49990305-2420e100-ffb8-11e8-9967-3c276f35f597.png)

**Comment by iYiming** [comment]
AdhocSDK getFlag 接口会先从本地找数据 然后根据时间间隔（默认 1 小时）如果超过 1  小时的时间间隔，会从服务器拉取最新的 flags 试验数据（不超过 1 小时，不会拉取最新 flags 数据）。下次再调用 getFlag 时就会返回最新的试验数据。至于超时问题，会有其他同事在微信群里回复。

**Comment by fangasvsass** [comment]
好的谢谢
