### ISSUE TITLE
example ios 中的release模式跑不起来 debug 可以

### ISSUE THREAD

**Issue by fangasvsass** [AppAdhoc/react-native-adhoc#8]

**Comment by fangasvsass** [comment]
![image](https://user-images.githubusercontent.com/8134572/59585831-f4dc5f80-9113-11e9-8a61-4d81d9f3addd.png)

**Comment by iYiming** [comment]
将 RNAdhoc 改成 release 运行下 然后再运行项目
![image](https://user-images.githubusercontent.com/3022390/59594722-f6635300-9126-11e9-82ab-f548a57727ac.png)
